services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "8883:8883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./certs:/certs:ro

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: admin
      DOCKER_INFLUXDB_INIT_PASSWORD: adminpass123
      DOCKER_INFLUXDB_INIT_ORG: bmw-demo
      DOCKER_INFLUXDB_INIT_BUCKET: vehicle_data
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: dev-only-token-change-me
    volumes:
      - influxdb-data:/var/lib/influxdb2

  telegraf:
    image: telegraf:1.30
    depends_on:
      - mosquitto
      - influxdb
    volumes:
      - ./docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./certs:/certs:ro
    environment:
      INFLUX_TOKEN: dev-only-token-change-me

  grafana:
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  influxdb-data:
  grafana-data: